config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [ :index, :new, :create, :show, :edit, :update ]
  root to: "users#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, length: { in: 6..20 }
  validates :email, uniqueness: true, length: { minimum: 6 }
  validates :password, length: { in: 6..25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      # raise StandardError.new "This is an exception"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.expect(user: [ :username, :email, :password ])
      # params.expect(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L46 Re Former" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<% if @user.errors.any? %>
  <div>
    <%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:
  </div>

  <div>
    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with method: :patch, model: @user do |form| %>
  <div>
    <%= form.label "Username: " %>
    <%= form.text_field :username, value: @user.username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email, value: @user.email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %><br>

<%= link_to "Homepage", root_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |u|%>
  <h3><%= link_to "#{u.username}", user_path(u) %> </h3>
  <ul>
    <li>Email: <%= u.email %> </li>
  </ul>
<% end %>

<%= link_to "Create Account", new_user_path %>

app/views/users/new.html.erb
<h1>Signup</h1>

<!-- Basic HTML Form -->

<!--
<form action="/users" method="post" accept-charset="UTF-8" data-turbo="false">
  <div>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </div>

  <div>
    <label for="username_input">Username: </label>
    <input type="text" id="username_input" name="user[username]"><br>
  </div>
  <div>
    <label for="email_input">Email: </label>
    <input type="text" id="email_input" name="user[email]" ><br>
  </div>
  <div>
    <label for="password_input">Password: </label>
    <input type="password" name="user[password]" id="password_input">
  </div>

  <div>
    <input type="submit" value="Submit">
  </div>
</form>
-->

<!-- Basic HTML Form using Rails Tag Helpers -->
<!--
<%= form_tag("/users")%>

  <div>
    <%= label_tag(:username, "Username: ") %>
    <%= text_field_tag(:username) %><br>
  </div>
  <div>
    <%= label_tag(:email, "Email: ") %>
    <%= text_field_tag(:email) %><br>
  </div>
  <div>
    <%= label_tag(:password, "Password: ") %>
    <%= password_field_tag(:password) %><br>
  </div>

  <div>
    <%= submit_tag("Submit") %>
  </div>
</form> -->

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label "Username: " %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email, value: "@gmail.com" %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Please don't do 1234" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %><br>

<%= link_to "Homepage", root_path %>

app/views/users/show.html.erb
<h1><%= @user.username %> </h1>

<ul>
  <li>Email: <%= @user.email %> </li>
</ul>

<br>
<%= link_to "Create Account", new_user_path %><br>
<%= link_to "Edit This Account", edit_user_path(@user.id) %><br>
<%= link_to "Homepage", root_path %><br>